#!/usr/bin/env bash
# configs/train_config.example.sh
#
# This file is "source"d by train.sh.
# Keep it pure bash: assign variables + arrays; avoid running commands.

TRAIN_PY="train.py"

num_gpus=4
ROOT_DIR="./Data/Grid4_New/CMIP6_MRI/graphs"
TEST_ROOT_DIR=""
STATION="Battery"

BATCH_SIZE=256
LR_LIST=("5e-3")

EPOCHS=300
HIDDEN_CHANNELS=128
NUM_LAYERS=2
DROPOUT=0.05
HEAD_DROPOUT=0.05
HISTORY_HOURS_LIST=(12)

SEED=42
MODEL="cnn"

TRAIN_RATIO="0.4545454545"
VAL_RATIO="0.0909090909"

USE_PMEAN=0
PMEAN_DIM=32
PERCEIVER_PMEAN_MODE="tokens"

LOSS_MODE_LIST=("mse")
TAIL_FRAC="0.05"
TAIL_LAMBDA_LIST=("0.10")
WMSE_Q_LIST=("95")
WMSE_ALPHA="4.0"
WMSE_S="0.10"
WMSE_USE_ABS="1"

SLOPE_LAMBDA_LIST=("0.01")
SLOPE_MASK_S_LIST=("0.10")
SLOPE_ROBUST="charb"
SLOPE_CHARB_EPS="1e-3"
SLOPE_HUBER_DELTA="0.05"

SCHEDULER="cosine"
ROP_METRIC="val_rmse_phys"

GATE_MODE="window"
GATE_BIAS_INIT="0.0"
TAIL_TANH_CLIP="0"
ALPHA_INIT_LOGIT="0"

NODE_READ_HEADS="8"
TIME_READ_HEADS="8"
TRANSFORMER_LAYERS="2"
TRANSFORMER_FF_MULT="4.0"
TRANSFORMER_DROPOUT="0.0"
MAX_TIME_STEPS="32"

STATION_JSON_DIR="./station_json"

X_NORM="robust"
X_P_LO="1.0"
X_P_HI="99.0"
X_NODES_PER_GRAPH="0"
X_CLIP="6.0"

X_AUG="1"
X_AUG_PROB="0.5"
X_AUG_SCALE="0.02"
X_AUG_BIAS="0.02"

DISABLE_OOD="1"

USE_AMP=1
AMP_DTYPE="bf16"
USE_TF32=1
TORCH_THREADS=1

NUM_WORKERS=0
PIN_MEMORY=0
PERSISTENT_WORKERS=0
PREFETCH_FACTOR=0
MP_CONTEXT="fork"

USE_TMUX="${USE_TMUX:-0}"

DO_CONDA=1
CONDA_SH="/scratch/projects/compilers/intel24.0/oneapi/intelpython/python3.9/etc/profile.d/conda.sh"
CONDA_ENV_1="base"
CONDA_ENV_2="/work/09575/$USER/conda_envs/torchpyg-cu128"
